# Generated by Django 4.0 on 2022-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aussie',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='cpav',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='fes',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='ibp',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='itp',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='microcorrente',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='polarizada',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='russa',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='tens',
            name='timer',
        ),
        migrations.AlterField(
            model_name='ibp',
            name='sweep_s',
            field=models.IntegerField(choices=[(1, 'Modo1'), (2, 'Modo2'), (3, 'Modo3')]),
        ),
    ]
